# Generated by Django 5.1.2 on 2024-10-27 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='user',
        ),
    ]
