# Generated by Django 5.1.2 on 2024-10-27 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_remove_contact_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='mobile_phone',
            new_name='phone_number',
        ),
    ]
